#!/usr/bin/env python3
"""Generate a Mesen2 Lua script that deterministically captures a frame.

Why this exists: blind controller input to *reach* gameplay is unreliable for
this game (it glitches through the menus and the --testRunner Lua sandbox is
unstable once input is driven). Loading a **savestate** that is already parked in
a level is deterministic and rock-solid. But `io.*` is sandboxed under
--testRunner, so the script cannot read the .mss itself — instead we **embed the
savestate as base64** in the generated Lua and decode it in-script.

Two more sandbox facts this encodes:
  * `emu.loadSavestate(data)` MUST be called inside a CPU **exec** callback, so we
    hook the native NMI vector ($00:977B for the USA ROM) and load on first hit.
  * `print()` is the only output channel; the PNG screenshot is base64-printed in
    `SB|` lines and the OAM sprite table in `CAP|` lines.

`emu.setInput` after a savestate load destabilises the sandbox, so this captures
a SINGLE frame. To see different parts of a level, make multiple savestates.

Usage:
  ./gen_savestate_capture.py <savestate.mss> [delay_frames] > /tmp/cap.lua
  MESEN_BIN=... DISPLAY=:0 $MESEN_BIN --testRunner <rom> /tmp/cap.lua > out.txt
  # then decode: grep '^SB|' out.txt | cut -c4- | base64 -d > shot.png

The capture dump contains ROM-derived pixels/OAM, so its OUTPUT is local-only and
must not be committed (this generator script is fine to commit).
"""
import base64
import sys

NMI_VECTOR = 0x00977B  # USA ROM native NMI; change for other regions.


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    mss = open(sys.argv[1], "rb").read()
    delay = int(sys.argv[2]) if len(sys.argv) > 2 else 20
    b64 = base64.b64encode(mss).decode()

    print(f"""-- AUTO-GENERATED by gen_savestate_capture.py (do not commit output)
local SS = [[{b64}]]
local T={{}}
do local s="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
   for i=1,#s do T[s:sub(i,i)]=i-1 end end
local function dec(s)
  local o={{}}; local i=1; local n=#s
  while i<=n do
    local c1=T[s:sub(i,i)] or 0; local c2=T[s:sub(i+1,i+1)] or 0
    local c3p=s:sub(i+2,i+2); local c4p=s:sub(i+3,i+3)
    local t=(c1<<18)|(c2<<12)|((T[c3p] or 0)<<6)|(T[c4p] or 0)
    o[#o+1]=string.char((t>>16)&255)
    if c3p~="=" and c3p~="" then o[#o+1]=string.char((t>>8)&255) end
    if c4p~="=" and c4p~="" then o[#o+1]=string.char(t&255) end
    i=i+4
  end
  return table.concat(o)
end
local E="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
local function enc(d)
  local o={{}}; local i=1; local n=#d
  while i<=n do
    local b1=d:byte(i); local b2=(i+1<=n) and d:byte(i+1) or 0; local b3=(i+2<=n) and d:byte(i+2) or 0
    local t=(b1<<16)|(b2<<8)|b3
    o[#o+1]=E:sub(((t>>18)&63)+1,((t>>18)&63)+1)..E:sub(((t>>12)&63)+1,((t>>12)&63)+1)..
      ((i+1<=n) and E:sub(((t>>6)&63)+1,((t>>6)&63)+1) or "=")..((i+2<=n) and E:sub((t&63)+1,(t&63)+1) or "=")
    i=i+3
  end
  return table.concat(o)
end
local function r8(a) return emu.read(a & 0xFFFF, emu.memType.snesMemory) end
local function r16(a) return r8(a)|(r8(a+1)<<8) end
local data=dec(SS)
local loaded=false
local load_frame=-1
local frame=0
emu.addMemoryCallback(function()
  if not loaded then loaded=true
    local ok=pcall(function() emu.loadSavestate(data) end)
    print("CAP|loadSavestate ok="..tostring(ok)); load_frame=frame end
end, emu.callbackType.exec, {NMI_VECTOR:#08x}, {NMI_VECTOR:#08x}, emu.cpuType.snes)
emu.addEventCallback(function()
  frame=frame+1
  if loaded and load_frame>=0 and frame==load_frame+{delay} then
    print(string.format("CAP|scene=%02X DD=%d DF=%d 1EF4=%04X 1EF8=%04X 1EE8=%d",
      r8(0x1EEA),r16(0xDD),r16(0xDF),r16(0x1EF4),r16(0x1EF8),r16(0x1EE8)))
    for s=0,63 do local o=s*4
      local x=emu.read(o,emu.memType.snesSpriteRam); local y=emu.read(o+1,emu.memType.snesSpriteRam)
      local t=emu.read(o+2,emu.memType.snesSpriteRam); local a=emu.read(o+3,emu.memType.snesSpriteRam)
      if y<224 and not (x==240 and y==240) then
        print(string.format("CAP|OAM #%d %3d %3d t=%02X a=%02X",s,x,y,t,a)) end end
    local e=enc(emu.takeScreenshot())
    for i=1,#e,200 do print("SB|"..e:sub(i,i+199)) end
    print("CAP|END"); emu.stop(0)
  end
  if frame>=600 then print("CAP|no-load"); emu.stop(0) end
end, emu.eventType.startFrame)
print("CAP|armed")""")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
